name: DyedBackpacks
version: ${project.version}
author: TheBusyBiscuit
description: Дополнение к Slimefun на разноцветные рюкзаки
website: https://github.com/TheBusyBiscuit/DyedBackpacks

main: io.github.thebusybiscuit.dyedbackpacks.DyedBackpacks
depend: [Slimefun]

api-version: 1.14